package exceptionhandling;

public class Tester7 {

	public static void main(String[] args) 
	{
		System.out.println("Main ");
		class.forName("Hey");
		System.out.println("Main Ends");
		// complie time error because it is checked exception have not developed try and catch

	}

}
